/**
 * postMessage protocol between AppHost (React) and CanvasFrame (iframe runtime).
 * All messages are strongly typed. sender must set { targetOrigin: '*' } when
 * using srcdoc iframes (origin is 'null').
 */

// ─── Host → Runtime ─────────────────────────────────────────────────────────

export type HostMessage =
  | InitMessage
  | PatchMessage
  | RequestHtmlMessage
  | DisableScriptsMessage
  | InsertImageMessage
  | DeleteElementMessage
  | SelectElementMessage
  | SetModeMessage
  | ZOrderMessage;

/** Canvas interaction mode. `edit` = content editing, `drag` = freeform transform. */
export type InteractionMode = 'edit' | 'drag';

/**
 * Switch the in-iframe interaction mode. The two modes are strictly exclusive:
 * `edit` enables click-select + double-click inline editing (no handles, no
 * dragging); `drag` enables move/resize/delete with handles (no inline editing).
 */
export interface SetModeMessage {
  type: 'set-mode';
  mode: InteractionMode;
}

export interface InitMessage {
  type: 'init';
  /** Serialized <section class="slide"> outer HTML for the current page */
  sectionHtml: string;
  /** file:// or blob: base URL so relative asset paths resolve */
  assetsBaseUrl: string;
}

export interface PatchMessage {
  type: 'patch';
  /** CSS path generated by runtime's buildStableSelector() */
  selector: string;
  ops: PatchOp[];
}

export type PatchOp =
  | { kind: 'text'; value: string }
  | { kind: 'attr'; name: string; value: string | null }
  | { kind: 'style'; name: string; value: string | null }
  | { kind: 'class'; add?: string[]; remove?: string[] };

/**
 * Insert a new <img> as an absolutely-positioned, freely-transformable element.
 * Position/size are percentages of the 1280x720 slide so they are
 * resolution-independent and export-stable. The host generates `id` (used as a
 * stable `data-hds-id` selector) and resolves `src` (blob: in folder mode,
 * data: URI in single-file mode) before sending.
 */
export interface InsertImageMessage {
  type: 'insert-image';
  id: string;
  src: string;
  leftPct: number;
  topPct: number;
  widthPct: number;
}

export interface DeleteElementMessage {
  type: 'delete-element';
  selector: string;
}

/**
 * Re-select an element by selector. The host sends this after the iframe
 * reloads (which happens whenever the slide HTML is replaced) so the in-iframe
 * selection overlay / transform handles are restored without a manual re-click.
 */
export interface SelectElementMessage {
  type: 'select-element';
  selector: string;
}

/**
 * Re-stack a free (positioned) element relative to the other free shapes on the
 * slide. The runtime owns the ordering logic (it sees every `[data-hds-id]`
 * element), so the host only names the element and the intent. A flowing element
 * is detached first so its z-index actually takes effect.
 *   front    – move above all other free elements
 *   back     – move below all other free elements
 *   forward  – swap with the element one layer above
 *   backward – swap with the element one layer below
 */
export interface ZOrderMessage {
  type: 'z-order';
  selector: string;
  op: 'front' | 'back' | 'forward' | 'backward';
}

export interface RequestHtmlMessage {
  type: 'request-html';
}

export interface DisableScriptsMessage {
  type: 'disable-scripts';
  /** true = move <script> to <template>, false = restore */
  disabled: boolean;
}

// ─── Runtime → Host ─────────────────────────────────────────────────────────

export type RuntimeMessage =
  | ReadyMessage
  | SelectMessage
  | ClearSelectMessage
  | PatchedMessage
  | ResponseHtmlMessage
  | RuntimeErrorMessage;

export interface ReadyMessage {
  type: 'ready';
}

export interface SelectMessage {
  type: 'select';
  selector: string;
  /** Element tag for attribute panel hints */
  tagName: string;
  bbox: SerializedDOMRect;
  /** Computed style snapshot for property panel pre-fill */
  styleSnapshot: StyleSnapshot;
  /** Selected element attributes relevant to the property panel (href, target, …) */
  attrs?: Record<string, string>;
  /** Current text content for back-filling the text editor in the panel */
  text?: string;
  /**
   * Stacking position among free (`data-hds-id`) elements, when the selection is
   * a free shape. `index` is 1-based; `count` is the total number of free shapes.
   * Absent for plain flowing elements that carry no stacking order yet.
   */
  layer?: LayerInfo;
  /**
   * Geometry in slide-native (1280×720) coordinates, derived from offset metrics
   * so the panel readout is resolution-independent (unlike the scaled `bbox`).
   */
  rect?: SlideRect;
}

export interface LayerInfo {
  index: number;
  count: number;
}

export interface SlideRect {
  left: number;
  top: number;
  width: number;
  height: number;
}

export interface ClearSelectMessage {
  type: 'clear-select';
}

export interface PatchedMessage {
  type: 'patched';
  /** Full outer HTML of the <section class="slide"> after patch */
  html: string;
}

export interface ResponseHtmlMessage {
  type: 'response-html';
  html: string;
}

export interface RuntimeErrorMessage {
  type: 'error';
  code: string;
  message: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

export interface SerializedDOMRect {
  x: number;
  y: number;
  width: number;
  height: number;
  top: number;
  left: number;
  bottom: number;
  right: number;
}

export interface StyleSnapshot {
  fontSize: string;
  fontWeight: string;
  color: string;
  textAlign: string;
  textDecoration: string;
}
